version: "3.8"

services:
  app:
    build:
      context: .
      target: development
    image: github-explorer:dev
    container_name: github-explorer-dev
    ports:
      - "3001:3001"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_BASE_URL=https://api.github.com
      - VITE_PORT=3001
    restart: unless-stopped
    stdin_open: true # for React DevTools
    tty: true # for color output
